# Generated by Django 2.0.6 on 2018-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_message_is_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_def',
            field=models.CharField(default='тема форума', max_length=1000),
            preserve_default=False,
        ),
    ]
