# Generated by Django 2.0.6 on 2018-06-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_theme_theme_def'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_fav',
        ),
    ]
