# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.FloatField()),
                ('height', models.FloatField()),
                ('neck', models.FloatField()),
                ('sleeves', models.FloatField()),
                ('shoulder', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('s', models.FloatField()),
                ('qx', models.FloatField()),
                ('qy', models.FloatField()),
                ('qz', models.FloatField()),
                ('qw', models.FloatField()),
                ('constructed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Constructed')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Part')),
            ],
        ),
    ]
