# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_constructed_part_partsinplaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsinplaces',
            name='constructed',
        ),
        migrations.RemoveField(
            model_name='partsinplaces',
            name='part',
        ),
        migrations.DeleteModel(
            name='Constructed',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PartsInPlaces',
        ),
    ]
