# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bucket_category_colour_detail_material_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Colour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Size'),
            preserve_default=False,
        ),
    ]
