# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartsInPlaces',
            new_name='PartsInPlace',
        ),
    ]
