# Generated by Django 2.0.6 on 2018-06-24 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_remove_constructed_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructed',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 24, 13, 52, 50, 872071, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
