# Generated by Django 2.0.6 on 2018-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_constructed_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructed',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
